AWS_PRIVATE_NODE_CIDR: 10.0.0.0/24
AWS_PUBLIC_NODE_CIDR: 10.0.1.0/24
AWS_VPC_CIDR: 10.0.0.0/16
CLUSTER_CIDR: 100.96.0.0/11
AWS_SSH_KEY_NAME: tkg-default
CONTROL_PLANE_MACHINE_TYPE: t3.medium
NODE_MACHINE_TYPE: t3.medium