apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dex
  namespace: tanzu-system-auth
spec:
  virtualhost:
    fqdn: dex.foo.bar
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: dexsvc
      port: 443
  routes:
  - match: /
    services:
    - name: kuard
      port: 80
