apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd
  namespace: argocd
spec:
  virtualhost:
    fqdn: YOUR_VALUE
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: argocd-server
      port: 443
  routes:
  - match: /
    services:
    - name: kuard
      port: 80