vsphere:
  vcenterserver: 'vcsa-01.haas-461.pez.pivotal.io'
  vcenterUser: 'administrator@vsphere.local'
  vcenterPwd: 'vcenterPwd'
  dataCenter: 'Datacenter'
  network: 'Extra'
  datastore: 'LUN01'
  resourcepool: '/Datacenter/host/Cluster/Resources/tkg'
  sshKey: 'ssh-rsa ...'
  folder: '/Datacenter/vm/tkg'
  ovafolder: /path_to_ova_folder
  phtonosova: photon-3-v1.17.3_vmware.2.ova
  haproxyova: 'photon-3-capv-haproxy-v0.6.3_vmware.1.ova'

dns:
  mgmt:
    name: '*.mgmt.tkg.lab.yourdomain.com'
  svc:
    name: '*.svc.tkg.lab.yourdomain.com'
  workload:
    name: '*.app.tkg.lab.yourdomain.com'

aws:
  region: us-west-2
  AWS_AMI_ID: ami-074a82cfc610da035
  AWS_NODE_AZ: us-west-2a
  access-key-id: access-key-id
  secret-access-key: secret-access-key
  dns:
    hosted-zone-id:  hosted-zone-id

mgmtCluster:
  name: tkg-mgmt-cluster
svcCluster:
  name: shared-services-cluster
  gangway: gangway.svc.tkg.lab.yourdomain.com
  secret: supersecret
  workdernodes: 2
wlCluster:
  name: workload-cluster-aws
  gangway: gangway.app.tkg.lab.yourdomain.com
  secret: supersecret
  workdernodes: 2
oidc:
  oidcUrl: oidcUrl
  oidcClientId: oidcClientId
  oidcClientSecret: oidcClientSecret

dex:
  host: dex.mgmt.tkg.lab.jkcloudmesh.com

wavefront:
  apiKey: apiKey

vmware:
  id: email@vmware.com

elasticsearch:
  host: elasticsearch.svc.tkg.lab.yourdomain.com
  port: 80
kibana:
  host: kibana.svc.tkg.lab.yourdomain.com
  