apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  namespace: acme-fitness
  labels:
    app: acmefit
spec:
  storageClassName: aws-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi